### ISSUE TITLE
404 on stylesheets

### ISSUE THREAD

**Issue by icp1994** [void-linux/buildbot-theme#4]
![image](https://github.com/user-attachments/assets/c6f83ec5-7b2a-4af2-8897-2c44f1058bb4)
![image](https://github.com/user-attachments/assets/8e401947-e2c4-4375-92bc-8a2114c2e03c)

**Comment by leahneukirchen** [comment]
Aha, that explains the 404 I see quickly flashing up on reload perhaps?

**Comment by classabbyamp** [comment]
sounds like https://github.com/buildbot/buildbot/issues/7439 i think?

**Comment by classabbyamp** [comment]
void_view has no scripts.js (intentionally), and grid_view is from upstream

**Comment by icp1994** [comment]
The sidebar looks fine in Firefox but messed up in Vivaldi for some reason.

**Comment by classabbyamp** [comment]
vivaldi (mobile and desktop) is what i use most exclusively and it's been fine for me

**Comment by icp1994** [comment]
Weird - in my end it looks like the shot I posted. In fact, that's the reason why I looked at the browser console. It was working fine last I checked, probably a week ago.

**Comment by icp1994** [comment]
Accidentally figured it out - some weird page zoom issue.

https://github.com/user-attachments/assets/b36b601f-cab7-4d96-a5fc-9931ba5a942c

**Comment by classabbyamp** [comment]
huh weird. might be something to report upstream

**Comment by icp1994** [comment]
In case anyone unfortunate enough to stumble across this, I have managed to "fix" this accidentally yesterday. The issue was apparently with wayland fractional scaling and how chromium (vivladi) handles it while rendering windows. I have always had vivaldi running in wayland backed (via --ozone-platform=wayland flag) but did not know about the UI scaling flags.

![Image](https://github.com/user-attachments/assets/2aa3bafc-ee97-4473-b328-1160aa2f29d5)

With these two enabled, the page renders as expected. FWIW I have `wlr-randr --output eDP-1 --scale 1.4` on startup which is the primary cause of the "bug".
